//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PassengerCount { get; set; }
        public int PilotId { get; set; }
        public int ScheduleId { get; set; }
    
        public virtual Pilot Pilot { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
